export const VEHICLES_SERVICE = 'VEHICLES_SERVICE';
export const EVENTS_SERVICE = 'EVENTS_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const MAINTENANCES_SERVICE = 'MAINTENANCES_SERVICE';
export const NOTIFICATIONS_SERVICE = 'NOTIFICATIONS_SERVICE';
